### ISSUE TITLE
Waf: The wscript in '/usr/ports/audio/stegosaurus-lv2/work/stegosaurus-851bd99' is unreadable

### ISSUE THREAD

**Issue by yurivict** [thunderox/stegosaurus-old-version#15]
```
Waf: The wscript in '/usr/ports/audio/stegosaurus-lv2/work/stegosaurus-851bd99' is unreadable
Traceback (most recent call last):
  File "/usr/ports/audio/stegosaurus-lv2/work/stegosaurus-851bd99/.waf3-1.8.5-19a841cd1d216acf003e0ae1045c9763/waflib/Scripting.py", line 93, in waf_entry_point
    set_main_module(os.path.join(Context.run_dir,Context.WSCRIPT_FILE))
  File "/usr/ports/audio/stegosaurus-lv2/work/stegosaurus-851bd99/.waf3-1.8.5-19a841cd1d216acf003e0ae1045c9763/waflib/Scripting.py", line 118, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/usr/ports/audio/stegosaurus-lv2/work/stegosaurus-851bd99/.waf3-1.8.5-19a841cd1d216acf003e0ae1045c9763/waflib/Context.py", line 329, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/usr/ports/audio/stegosaurus-lv2/work/stegosaurus-851bd99/wscript", line 40
    if sys.maxint >= 9223372036854775807:
                                        ^
TabError: inconsistent use of tabs and spaces in indentation
```

It appears that you use python-2. Python 2 is EOLed. Please use python-3.

**Comment by thunderox** [comment]
Yes this plugin was started 5+ years ago and the install uses python 2 I'm just about to fix it (hopefully).

**Comment by thunderox** [comment]
Should work with python3 now
